#!/usr/bin/env python3

import pandas
pd = pandas.read_csv("proposals.csv")
print("Auto generating papers.tab")
with open("papers.tab", "w+") as tab:
    tab.write("#  AUTOGENERATED - ensure to make a copy if you edit\n")
    for pdi, pdr in pd.iterrows():
        surname = pdr["name"].split(" ")[-1]
        name = " ".join(pdr["name"].split(" ")[:-1])
        pid = pdr["paper_id"]
        tab.write(f"{surname}, {name}     ; {pid}\n")
        print(f"Processed {pid}")
