#! /bin/csh -f
#
#  Recursively clean selected directories of MAC files that typically are trojan'd via MAC's tar program
#
#  See also:   https://macpaw.com/how-to/remove-ds-store-files-on-mac
#
#  Peter Teuben

if ($#argv == 0) then
   echo "Usage:  $0 [-n] dirname(s)"
   echo ""
   echo "This script will find all nasty files MAC's tar program seem to hide in your tree"
   echo 'Currently:  .DS_Store __MACOSX and ._* files'
   echo 'Please tell your MAC friends to install a real tar, e.g. gnu tar'
   echo 'E.g. "brew install gnu-tar"'
   echo 'Options: '
   echo '  -n    show which files it finds, but not delete them'
   exit 0
endif

#  by default show files and delete them
set fargs = (-print -exec rm -rf '{}' \;)

#  loop over all directories
foreach dir ($*)
  if (X$dir == X-n) then
    set fargs = (-print)
    continue
  endif
  echo DIR1: $dir
  find $dir -name .DS_Store $fargs
  find $dir -name ._\*      $fargs
  find $dir -name __MACOSX  $fargs
end  
