#! /usr/bin/env python
#
# take a self-contained ADASS paper and output the embedable version
#
# TODO?
# Should it produce toc entries for inclusion, e.g.
#   \tocinsertentry[r]{ TITLE }{A.~Aloisi (Invited Speaker)}{authors/I1-2_inc} 

import sys


def read1(filename):
    """ read tex file into lines for processing
    """
    f = open(filename)
    lines = f.readlines()
    f.close()
    return lines

test = """
% test section
\documentclass[11pt,twoside]{article}
\usepackage{asp2014}

\aspSuppressVolSlug
\resetcounters

\bibliographystyle{asp2014}

\begin{document}

The document...

%\aindex{Author1}
%\aindex{Coauthor2}

bibliography{O5-3}

\end{document}

"""

triggers = []
triggers.append([True,"\\documentclass",   0])
triggers.append([True,"\\usepackage",      0])
triggers.append([True,"\\begin{document}", 0])
triggers.append([True,"\\end{document}",   0])
triggers.append([False,"%\\aindex",        0])
#triggers.append([True,"\\bibliography",   0])




if len(sys.argv) == 1:
    print("Usage: %s name.tex" % sys.argv[0])
    sys.exit(0)

paper = sys.argv[1]
lines = read1(paper)


print("%% DO NOT EDIT THIS FILE, generated by TEX2INC")

for l in lines:
    triggered = False
    for t in triggers:
        if l.find(t[1]) == 0:
            t[2] = t[2] + 1
            if t[0]:
                print("%%TEX2INC %s" % l.strip())
            else:
                print("%s" % l[1:].strip())
            triggered = True
            continue
    if not triggered:
        print(l.strip())

# summary
nbad = 0
missing = []
for t in triggers:
    if t[2]==0:
        nbad = nbad + 1
        missing.append(t[1])
    print("%%INC %d %s" % (t[2],t[1]))
if nbad > 0:
    print("%% Warning, missing items: %s" % str(missing))
else:
    print("%% tex2inc OK")
